import re

products = []

# CMT ORANGE TOOLS - ACCESORIOS / HERRAMIENTAS / MEDICION
products.append({"name":"CMT REMATADOR DE CANTOS DOBLE DET-001","model":"DET-001","desc":"Rematador de cantos doble CMT Orange Tools. Codigo DET-001.","short":"Rematador cantos doble DET-001","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/DET-001.jpg"})
products.append({"name":"CMT RETESTADOR MANUAL PARA CANTOS DET-002","model":"DET-002","desc":"Retestador manual para cantos CMT Orange Tools. Codigo DET-002.","short":"Retestador manual cantos DET-002","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/DET-002.png"})
products.append({"name":"CMT CORTATIRAS MANUAL DET-003","model":"DET-003","desc":"Cortatiras manual CMT Orange Tools. Codigo DET-003.","short":"Cortatiras manual DET-003","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/DET-003.jpg"})
products.append({"name":"CMT GRADUADOR MAGNETICO DE CUCHILLAS CMT792","model":"CMT792","desc":"Graduador magnetico de cuchillas CMT Orange Tools. Codigo CMT792.","short":"Graduador magnetico cuchillas CMT792","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/CMT792.webp"})
products.append({"name":"CMT EQUIPO DE EBANISTERIA PRENSAS Y PERFORACIONES PPJ-002","model":"PPJ-002","desc":"Equipo de ebanisteria, prensas y perforaciones CMT Orange Tools. Codigo PPJ-002.","short":"Equipo ebanisteria prensas PPJ-002","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/PPJ-002.jpg"})
products.append({"name":"CMT PRENSA PARA PIEZAS PEQUEÑAS PTC-1","model":"PTC-1","desc":"Prensa para piezas pequeñas CMT Orange Tools. Codigo PTC-1.","short":"Prensa piezas pequenas PTC-1","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/PTC-1.jpg"})
products.append({"name":"CMT PRENSAS AJUSTABLES PARA JUNTAS DE ESQUINA CFC-002","model":"CFC-002","desc":"Prensas ajustables para juntas de esquina CMT Orange Tools. Codigo CFC-002.","short":"Prensas ajustables juntas esquina CFC-002","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/CFC-002.jpg"})
products.append({"name":"CMT LAPIZ CUADRADO PARA CARPINTERO PCL-1","model":"PCL-1","desc":"Lapiz cuadrado para carpintero CMT Orange Tools. Codigo PCL-1.","short":"Lapiz cuadrado carpintero PCL-1","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/PCL-1.jpg"})
products.append({"name":"CMT METRO PLEGABLE PLASTICO PARA CARPINTERO FR2M","model":"FR2M","desc":"Metro plegable plastico para carpintero CMT Orange Tools. Codigo FR2M.","short":"Metro plegable plastico FR2M","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/FR2M.png"})
products.append({"name":"CMT CUADRADO DE ANGULO DIGITAL CDG-001","model":"CDG-001","desc":"Cuadrado de angulo digital CMT Orange Tools. Codigo CDG-001.","short":"Cuadrado angulo digital CDG-001","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/CDG-001.jpg"})
products.append({"name":"CMT MEDIDOR DE ANGULOS DIGITAL DAG-001","model":"DAG-001","desc":"Medidor de angulos digital CMT Orange Tools. Codigo DAG-001.","short":"Medidor angulos digital DAG-001","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/DAG-001.jpg"})
products.append({"name":"CMT MEDIDOR DE PROFUNDIDAD DIGITAL DHG-001","model":"DHG-001","desc":"Medidor de profundidad digital CMT Orange Tools. Codigo DHG-001.","short":"Medidor profundidad digital DHG-001","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/DHG-001.jpg"})
products.append({"name":"CMT KIT PARA PERFORAR VIDRIOS CERAMICA 552.001.05","model":"552.001.05","desc":"Kit para perforar vidrios y ceramica CMT Orange Tools. Codigo 552.001.05.","short":"Kit perforar vidrios ceramica 552.001.05","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/552.001.05.jpg"})
products.append({"name":"CMT KIT PARA PERFORAR VIDRIOS CERAMICA CON CHUPON 552.001.06","model":"552.001.06","desc":"Kit para perforar vidrios y ceramica con chupon CMT Orange Tools. Codigo 552.001.06.","short":"Kit perforar vidrios ceramica chupon 552.001.06","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/552.701.06.jpg"})
products.append({"name":"CMT KIT DE DISCOS PARA RANURAR 230.012.08","model":"230.012.08","desc":"Kit de discos para ranurar CMT Orange Tools. Codigo 230.012.08.","short":"Kit discos ranurar 230.012.08","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/230.012.08.jpg"})
products.append({"name":"CMT FORMULA 2050 PARA LIMPIEZA DE DISCOS Y MECHAS 998.001.01","model":"998.001.01","desc":"Formula 2050 para limpieza de discos y mechas CMT Orange Tools. Codigo 998.001.01.","short":"Formula 2050 limpieza discos mechas 998.001.01","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/998.001.01.jpg"})
products.append({"name":"CMT FORMULA 2050 PARA LIMPIEZA DE DISCOS Y MECHAS GALON 998.001.03","model":"998.001.03","desc":"Formula 2050 para limpieza de discos y mechas galon CMT Orange Tools. Codigo 998.001.03.","short":"Formula 2050 limpieza discos galon 998.001.03","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/998.001.03.jpg"})
products.append({"name":"CMT GUIA DE BORDE PARA RANURAS PGD-1","model":"PGD-1","desc":"Guia de borde para ranuras CMT Orange Tools. Codigo PGD-1.","short":"Guia borde ranuras PGD-1","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/PGD-1.jpg"})
products.append({"name":"CMT REPLICADOR DE CONTORNOS CDG-001R","model":"CDG-001R","desc":"Replicador de contornos CMT Orange Tools. Codigo CDG-001R.","short":"Replicador contornos CDG-001R","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/CDG-001.jpg"})
products.append({"name":"CMT CUCHILLAS PARA CORTA TIRAS DET-003K","model":"DET-003K","desc":"Cuchillas para corta tiras CMT Orange Tools. Codigo DET-003K.","short":"Cuchillas corta tiras DET-003K","cat":"Accesorios","sub":"Accesorios","img":""})
products.append({"name":"CMT CABEZAL MODULAR P/MONTURA DE BISAGRAS CMT333-4595","model":"CMT333-4595","desc":"Cabezal modular para montura de bisagras CMT Orange Tools. Codigo CMT333-4595.","short":"Cabezal modular bisagras CMT333-4595","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/CMT333-4595.jpg"})
products.append({"name":"CMT BASE P/SISTEMA DE BISAGRAS SIMILAR A LA TRIMATIC S.M CMT333","model":"CMT333","desc":"Base para sistema de bisagras similar a la Trimatic S.M CMT Orange Tools. Codigo CMT333.","short":"Base bisagras Trimatic CMT333","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/CMT333.jpg"})
products.append({"name":"CMT MEDIDOR DIGITAL DE HUMEDAD DMM-001","model":"DMM-001","desc":"Medidor digital de humedad CMT Orange Tools. Codigo DMM-001.","short":"Medidor digital humedad DMM-001","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/DMM-001.jpg"})
products.append({"name":"CMT BOLSO PARA CARPINTERO PORTAHERRAMIENTAS BAG-001","model":"BAG-001","desc":"Bolso para carpintero portaherramientas CMT Orange Tools. Codigo BAG-001.","short":"Bolso carpintero portaherramientas BAG-001","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/BAG-001.jpg"})
products.append({"name":"CMT MARCADORES DE AGUJEROS PROFUNDOS PCL-3D","model":"PCL-3D","desc":"Marcadores de agujeros profundos CMT Orange Tools. Codigo PCL-3D.","short":"Marcadores agujeros profundos PCL-3D","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/PCL-3D.jpg"})
products.append({"name":"CMT JUEGO DESTORNILLADOR DINANOMETRICO TW-006","model":"TW-006","desc":"Juego destornillador dinanometrico CMT Orange Tools. Codigo TW-006.","short":"Juego destornillador dinanometrico TW-006","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/TW-006.jpg"})
products.append({"name":"CMT LLAVE DINAMOMETRICA INTERCAMBIABLE TW-200","model":"TW-200","desc":"Llave dinamometrica intercambiable CMT Orange Tools. Codigo TW-200.","short":"Llave dinamometrica intercambiable TW-200","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/TW-200.jpg"})
products.append({"name":"CMT INSERCION DE SECTOR ER16 Y ER20 TW-2836","model":"TW-2836","desc":"Insercion de sector ER16 y ER20 CMT Orange Tools. Codigo TW-2836.","short":"Insercion sector ER16 ER20 TW-2836","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/tw-2836.jpg"})
products.append({"name":"CMT INSERCION DE SECTOR ER25 TW-4045","model":"TW-4045","desc":"Insercion de sector ER25 CMT Orange Tools. Codigo TW-4045.","short":"Insercion sector ER25 TW-4045","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/TW-4045.jpg"})
products.append({"name":"CMT INSERCION DE SECTOR ER32 TW-5055","model":"TW-5055","desc":"Insercion de sector ER32 CMT Orange Tools. Codigo TW-5055.","short":"Insercion sector ER32 TW-5055","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/TW-5055.webp"})
products.append({"name":"CMT INSERCION DE SECTOR ER40 Y EOC25 TW-5862","model":"TW-5862","desc":"Insercion de sector ER40 y EOC25 CMT Orange Tools. Codigo TW-5862.","short":"Insercion sector ER40 EOC25 TW-5862","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/TW-5862.webp"})
products.append({"name":"CMT ADAPTADOR DE TRINQUETE S2=3/8 TW-AO95","model":"TW-AO95","desc":"Adaptador de trinquete S2=3/8 CMT Orange Tools. Codigo TW-AO95.","short":"Adaptador trinquete 3/8 TW-AO95","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/tw-AO95.jpg"})
products.append({"name":"CMT ADAPTADOR DE TRINQUETE S2=1/2 TW-A127","model":"TW-A127","desc":"Adaptador de trinquete S2=1/2 CMT Orange Tools. Codigo TW-A127.","short":"Adaptador trinquete 1/2 TW-A127","cat":"Accesorios","sub":"Accesorios","img":"/assets/product-images/cmt-orange-tools/TW-A127.webp"})

# Generate TypeScript entries
lines = []
for p in products:
    slug = p["name"].lower().replace('"','').replace('/','-').replace(' ','-').replace('+','-')
    slug = re.sub(r'-+', '-', slug).strip('-')
    name = p["name"].replace('"', '\\"')
    desc = p["desc"].replace('"', '\\"')
    short = p["short"].replace('"', '\\"')
    lines.append(f'  {{ id: "cmt-ot-{slug}", slug: "{slug}", name: "{name}", brand: "CMT Orange Tools", model: "{p["model"]}", description: "{desc}", shortDescription: "{short}", category: "{p["cat"]}", subcategory: "{p["sub"]}", image: "{p["img"]}" }},')

with open("new_products3.txt", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Total products: {len(products)}")
print("Written to new_products3.txt")
