import re

path = 'src/lib/data/products.ts'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

products = []
idx = 0
while True:
    m = re.search(r'\{', content[idx:])
    if not m:
        break
    s = idx + m.start()
    depth = 0
    for i in range(s, len(content)):
        if content[i] == '{':
            depth += 1
        elif content[i] == '}':
            depth -= 1
            if depth == 0:
                block = content[s:i+1]
                id_m = re.search(r"id:\s*['\"](.+?)['\"]", block)
                if id_m:
                    products.append({'id': id_m.group(1), 'text': block})
                idx = i + 1
                break
    else:
        break

print(f"Before: {len(products)}")

# Remove second occurrence of duplicates (keep the one with more content/image)
seen = {}
clean = []
removed = 0
for p in products:
    if p['id'] in seen:
        # Keep the one with longer text (more data)
        if len(p['text']) > len(seen[p['id']]['text']):
            # Replace: remove old, keep new
            clean = [x for x in clean if x['id'] != p['id']]
            clean.append(p)
            seen[p['id']] = p
        removed += 1
        continue
    seen[p['id']] = p
    clean.append(p)

print(f"After: {len(clean)}")
print(f"Removed: {removed}")

# Verify
ids = [p['id'] for p in clean]
from collections import Counter
dupes = {k: v for k, v in Counter(ids).items() if v > 1}
if dupes:
    print(f"Still duplicated: {dupes}")
else:
    print("All unique")

# Rebuild
products_text = ',\n'.join(p['text'] for p in clean)

new_content = '// @ts-nocheck\n'
new_content += '/* eslint-disable @typescript-eslint/no-unused-vars, react-hooks/exhaustive-deps */\n'
new_content += '/* AUTO-GENERATED by manage-products.py \u2014 DO NOT EDIT BY HAND */\n'
new_content += 'export interface Product {\n'
new_content += '  id: string;\n'
new_content += '  slug: string;\n'
new_content += '  brand: string;\n'
new_content += '  name: string;\n'
new_content += '  model: string;\n'
new_content += '  image: string;\n'
new_content += '  images: string[];\n'
new_content += '  category: string;\n'
new_content += '  subcategory: string;\n'
new_content += '  description: string;\n'
new_content += '  shortDescription: string;\n'
new_content += '  features: string[];\n'
new_content += '  specs: { [key: string]: string };\n'
new_content += '  featured: boolean;\n'
new_content += '  price?: string;\n'
new_content += '  videoId?: string;\n'
new_content += '}\n\n'
new_content += 'export const products: Product[] = [\n'
new_content += products_text + '\n'
new_content += '];\n'

# Append productSubcategories and productCategories
with open('scripts/extracted_arrays.txt', 'r', encoding='utf-8') as f:
    arrays = f.read()

new_content += '\n\n' + arrays

with open(path, 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f"Written {len(clean)} products")
