import re

path = 'src/lib/data/products.ts'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

products = []
idx = 0
while True:
    m = re.search(r'\{', content[idx:])
    if not m:
        break
    s = idx + m.start()
    depth = 0
    for i in range(s, len(content)):
        if content[i] == '{':
            depth += 1
        elif content[i] == '}':
            depth -= 1
            if depth == 0:
                block = content[s:i+1]
                id_m = re.search(r"id:\s*['\"](.+?)['\"]", block)
                if id_m:
                    products.append({'id': id_m.group(1), 'text': block})
                idx = i + 1
                break
    else:
        break

print(f"Parsed {len(products)} products")

# Find all duplicate IDs
from collections import Counter
id_counts = Counter(p['id'] for p in products)
dup_ids = {k for k, v in id_counts.items() if v > 1}
print(f"Found {len(dup_ids)} duplicate IDs")

# Show all duplicates
for d in sorted(dup_ids):
    matches = [i for i, p in enumerate(products) if p['id'] == d]
    print(f"  {d} (indices: {matches})")

# Step 1: For each duplicate group, keep first occurrence, rename subsequent ones
# CMT OT exact duplicates: second occurrence is same content -> remove
# CMT Contractor K model: both have same ID but different content -> rename second
# Dakin: both have same ID but different content -> rename second

processed = set()
keep = []
remove_count = 0
rename_count = 0

for i, p in enumerate(products):
    pid = p['id']
    if pid not in dup_ids:
        keep.append(p)
        continue
    
    if pid in processed:
        # Second (or later) occurrence of duplicate
        # Check if it's an exact duplicate
        first_idx = None
        for j, q in enumerate(products):
            if q['id'] == pid:
                first_idx = j
                break
        
        if first_idx is not None and products[first_idx]['text'] == p['text']:
            # Exact duplicate - remove
            remove_count += 1
            continue
        else:
            # Different content - rename this one
            new_id = pid + '-2'
            p['id'] = new_id
            p['text'] = p['text'].replace(f"id: '{pid}'", f"id: '{new_id}'", 1)
            rename_count += 1
            keep.append(p)
    else:
        # First occurrence
        processed.add(pid)
        keep.append(p)

print(f"\nRemoved {remove_count} exact duplicates")
print(f"Renamed {rename_count} non-exact duplicates")

# Verify
ids = [p['id'] for p in keep]
dupes_check = [x for x in ids if ids.count(x) > 1]
if dupes_check:
    print(f"WARNING: Still have duplicates: {set(dupes_check)}")
else:
    print(f"All {len(keep)} products have unique IDs")

# Rebuild file
products_text = ',\n'.join(p['text'] for p in keep)

new_content = f'''// @ts-nocheck
/* eslint-disable @typescript-eslint/no-unused-vars, react-hooks/exhaustive-deps */
/* AUTO-GENERATED by manage-products.py — DO NOT EDIT BY HAND */
export interface Product {{
  id: string;
  slug: string;
  brand: string;
  name: string;
  model: string;
  image: string;
  images: string[];
  category: string;
  subcategory: string;
  description: string;
  features: string[];
  specs: {{ [key: string]: string }};
  featured: boolean;
  price?: string;
  videoId?: string;
}}

export const products: Product[] = [
{products_text}
];
'''

with open(path, 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f"Wrote {len(keep)} products to products.ts")
