import os, re

path = os.path.join(os.path.dirname(__file__), '..', 'src', 'lib', 'data', 'products.ts')
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

products = []
idx = 0
while True:
    m = re.search(r'\{', content[idx:])
    if not m:
        break
    s = idx + m.start()
    depth = 0
    for i in range(s, len(content)):
        if content[i] == '{':
            depth += 1
        elif content[i] == '}':
            depth -= 1
            if depth == 0:
                block = content[s:i+1]
                id_m = re.search(r"id:\s*['\"](.+?)['\"]", block)
                if id_m:
                    products.append({'id': id_m.group(1), 'text': block})
                idx = i + 1
                break
    else:
        break

print(f"Parsed {len(products)} products")

# Step 1: Rename CMT Contractor model K duplicates to -k suffix
cmt_k_ids = [
    'disco-madera-6-1-2-z36',
    'disco-madera-7-1-4-z24',
    'disco-madera-7-1-4-z40',
    'disco-madera-8-1-4-z24',
    'disco-madera-8-1-4-z40',
]

seen = {}
renamed = 0
for p in products:
    if p['id'] in cmt_k_ids:
        if p['id'] in seen:
            # This is the second one - rename to -k (the K model is the second one)
            new_id = p['id'] + '-k'
            p['id'] = new_id
            p['text'] = p['text'].replace(f"id: '{p['id'].replace('-k', '')}'", f"id: '{new_id}'", 1)
            renamed += 1
        else:
            seen[p['id']] = True

print(f"Renamed {renamed} CMT Contractor K duplicates")

# Step 2: Rename Dakin second occurrences to -z suffix
dakin_ids = [
    'cinta-ct-1-4-z4',
    'cinta-ct-1-2-z6',
    'cinta-ct-1-2-z10',
    'cinta-ct-1-2-z14',
]

seen2 = {}
renamed2 = 0
for p in products:
    if p['id'] in dakin_ids:
        if p['id'] in seen2:
            # This is the second one - rename with actual size
            new_id = p['id'] + '-1-1-4' if '1-4' in p['id'] else p['id'] + '-1-1-2'
            p['id'] = new_id
            p['text'] = p['text'].replace(f"id: '{p['id'].replace('-1-1-4', '').replace('-1-1-2', '')}'", f"id: '{new_id}'", 1)
            renamed2 += 1
        else:
            seen2[p['id']] = True

print(f"Renamed {renamed2} Dakin duplicates")

# Step 3: Remove CMT OT exact duplicates (second occurrence)
seen3 = {}
removed = 0
clean = []
for p in products:
    if p['id'] in seen3:
        removed += 1
        continue
    seen3[p['id']] = True
    clean.append(p)

print(f"Removed {removed} CMT OT exact duplicates")

# Step 4: Verify no duplicates remain
ids = [p['id'] for p in clean]
dupes = [x for x in ids if ids.count(x) > 1]
if dupes:
    print(f"WARNING: Still have duplicates: {set(dupes)}")
else:
    print(f"✓ All {len(clean)} products have unique IDs")

# Rebuild file
products_text = ',\n'.join(p['text'] for p in clean)

new_content = f'''// @ts-nocheck
/* eslint-disable @typescript-eslint/no-unused-vars, react-hooks/exhaustive-deps */
/* AUTO-GENERATED by manage-products.py — DO NOT EDIT BY HAND */
export interface Product {{
  id: string;
  slug: string;
  brand: string;
  name: string;
  model: string;
  image: string;
  images: string[];
  category: string;
  subcategory: string;
  description: string;
  features: string[];
  specs: {{ [key: string]: string }};
  featured: boolean;
  price?: string;
  videoId?: string;
}}

export const products: Product[] = [
{products_text}
];
'''

with open(path, 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f"Done! Wrote {len(clean)} products to products.ts")
